#!/usr/bin/env python3
"""Pin a pre-built container image on a Hugging Face Space (sdk: docker) via a thin Dockerfile + README."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def build_dockerfile(image_ref: str) -> bytes:
    return (
        "# syntax=docker/dockerfile:1.3\n"
        "# Auto-generated by CI: Space runs a pre-built image from the registry.\n"
        f"FROM {image_ref}\n"
    ).encode("utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-id", required=True, help="HF repo id: namespace/space-name")
    parser.add_argument("--image", required=True, help="Full image reference (registry.../name:tag)")
    parser.add_argument("--readme", type=Path, required=True)
    parser.add_argument("--token", required=True)
    args = parser.parse_args()

    try:
        from huggingface_hub import CommitOperationAdd, HfApi
    except ImportError:
        print("ERROR: install huggingface_hub (pip install huggingface_hub)", file=sys.stderr)
        raise SystemExit(2) from None

    readme_text = args.readme.read_text(encoding="utf-8")
    dockerfile = build_dockerfile(args.image)
    api = HfApi(token=args.token)
    api.create_commit(
        repo_id=args.repo_id,
        repo_type="space",
        operations=[
            CommitOperationAdd(path_in_repo="Dockerfile", path_or_fileobj=dockerfile),
            CommitOperationAdd(path_in_repo="README.md", path_or_fileobj=readme_text.encode("utf-8")),
        ],
        commit_message=f"ci: deploy {args.image}",
    )
    print(f"Committed Dockerfile + README to Space {args.repo_id}")


if __name__ == "__main__":
    main()
