#!/usr/bin/env sh
set -eu

cat > internal/httpapi/openapi_stub.go <<'GEN'
// Code generated by scripts/generate-openapi-stubs.sh; DO NOT EDIT.
package httpapi

// OpenAPIServer describes handlers defined by api/openapi.yaml.
// The concrete Gin wiring currently lives in router.go as a scaffold.
type OpenAPIServer interface {
	Healthz()
	Readyz()
	Metrics()
	Me()
}
GEN

echo "wrote internal/httpapi/openapi_stub.go"
